// Recetas estructuradas extraidas de Recetas.Mar.docx (importadas por script).
// Parte 1 de 2.
export interface RecetaImport {
  titulo: string;
  momento: 'COMIDA' | 'CENA' | 'AMBAS' | 'POSTRE';
  descripcion?: string;
  tiempo?: number | null;
  personas?: number | null;
  ingredientes: string[];
  pasos: string[];
}

export const RECETAS_A: RecetaImport[] = [
  {
    titulo: 'Aguacate relleno',
    momento: 'COMIDA',
    descripcion: 'Fresco, rápido y muy completo',
    tiempo: 25,
    personas: 2,
    ingredientes: ['Aguacates', 'Queso fresco', 'Piña en lata (reservar el jugo)', 'Tomate', 'Palitos de cangrejo', 'Langostinos', 'Mayonesa'],
    pasos: [
      'Vaciar con cuchara el aguacate y cortar en daditos junto con queso fresco, piña de lata también en daditos (reservar el jugo de la lata), tomate, palitos de cangrejo y langostinos.',
      'En un bol mezclamos todo con mayonesa y se le añade un poco de jugo de la lata.',
      'Rellenar las mitades del aguacate y servir frío.',
    ],
  },
  {
    titulo: 'Albóndigas agridulces',
    momento: 'COMIDA',
    descripcion: 'Albóndigas en salsa agridulce de naranja',
    tiempo: 45,
    personas: 4,
    ingredientes: ['Carne picada', 'Huevo', 'Cebolla', 'Sal', 'Pan rallado', 'Harina', 'Zumo de naranja', 'Mostaza', 'Vinagre de arroz', 'Kétchup', 'Azúcar moreno', 'Salsa de soja'],
    pasos: [
      'En el vaso de la batidora se echa un huevo y un trozo de cebolla y se tritura; se le echa a la carne junto con sal y pan rallado.',
      'Se hacen bolitas, se rebozan con harina y se fríen.',
      'En una sartén grande se prepara la salsa con: un vaso grande de zumo de naranja, una cucharada de mostaza, cuatro cucharadas de vinagre de arroz, dos cucharadas de kétchup, cuatro cucharadas de azúcar moreno y dos cucharadas de salsa de soja. Estas cantidades se calculan según la cantidad de albóndigas utilizado.',
      'Removemos bien y dejamos que hierva un poco añadiendo un poco de sal y por último se echan las albóndigas dejándolas hervir un poco con la salsa.',
      'Si hiciera falta se puede añadir un poco de harina para espesar la salsa.',
    ],
  },
  {
    titulo: 'Albóndigas de bacalao',
    momento: 'COMIDA',
    descripcion: 'Albóndigas de bacalao en salsa',
    tiempo: 60,
    personas: 4,
    ingredientes: ['Bacalao desalado', 'Perejil', 'Huevos', 'Pan rallado', 'Aceite', 'Cebolla', 'Almendras fritas', 'Vino blanco', 'Caldo de pescado', 'Sal', 'Pimienta', 'Azafrán', 'Harina'],
    pasos: [
      'Se desmiga el bacalao desalado y se pone en un bol junto con perejil picado, dos huevos y pan rallado; se reserva en el frigorífico durante 30 minutos.',
      'En una sartén con un poco de aceite se refríe una cebolla picadita, unas cuantas almendras fritas, un poco de vino blanco, un poco de agua y un poco de caldo de pescado, sal y pimienta, azafrán y se deja hervir.',
      'Las albóndigas se moldean, se rebozan en harina y se fríen.',
      'Se añaden a la salsa anterior dejando que hiervan un poquito.',
    ],
  },
  {
    titulo: 'Albóndigas con salsa de almendras',
    momento: 'COMIDA',
    descripcion: 'Albóndigas clásicas con salsa de almendras',
    tiempo: 55,
    personas: 4,
    ingredientes: ['Carne picada', 'Cebolla', 'Huevo', 'Pan rallado', 'Sal', 'Harina', 'Pan', 'Almendras', 'Aceite', 'Ajos', 'Coñac o vino blanco', 'Agua', 'Pimienta'],
    pasos: [
      'En el vaso de la batidora se echa un trozo de cebolla y un huevo y se tritura; se le añade a la carne junto con pan rallado y sal.',
      'Se hacen bolitas, se rebozan en harina y se fríen.',
      'En una sartén pequeña se fríe una rebanada de pan y unas cuantas almendras y se tritura.',
      'En otra sartén más grande se echa el aceite donde se ha frito el pan y, si hace falta, se le añade un poco más; se refríe una cebolla y dos ajos picaditos y cuando esté pochadito se le añade el pan y las almendras trituradas junto con medio vaso de coñac o vino blanco.',
      'Una vez que se evapore el alcohol, añadir un poco de agua, sal y pimienta y agregar las albóndigas dejando que hiervan un poco.',
    ],
  },
  {
    titulo: 'Bizcocho de Cola Cao',
    momento: 'POSTRE',
    descripcion: 'Bizcocho de chocolate con cobertura',
    tiempo: 75,
    personas: 8,
    ingredientes: ['Harina', 'Azúcar', 'Cola Cao', 'Bicarbonato', 'Levadura', 'Sal', 'Huevos', 'Leche', 'Aceite de girasol', 'Vainilla', 'Agua hirviendo', 'Nata líquida', 'Tableta de chocolate de cobertura', 'Papel de horno'],
    pasos: [
      'Mezclar la harina tamizada, el azúcar, el Cola Cao, el bicarbonato, la levadura y una pizca de sal. Remover todo.',
      'Hacer un hueco en el centro y echar 2 huevos, 200 ml de leche, 125 ml de aceite de girasol y una cucharadita de vainilla. Mezclar todo.',
      'Por último añadir 100/125 ml de agua hirviendo y mezclar.',
      'Poner papel de horno en el molde y hornear a 180º hasta que esté hecho.',
      'Cobertura: calentar en el microondas la nata con una tableta de chocolate de cobertura hasta derretir el chocolate y echarlo sobre el bizcocho.',
    ],
  },
  {
    titulo: 'Bocadillo campero',
    momento: 'CENA',
    descripcion: 'Bocata de mollete con pollo y huevo',
    tiempo: 20,
    personas: 2,
    ingredientes: ['Pan (mollete)', 'Mayonesa', 'Tomate', 'Lechuga', 'Filetes de pollo', 'Jamón de york', 'Queso en lonchas', 'Huevo'],
    pasos: [
      'Se tuesta el pan (mollete) y se unta con mayonesa.',
      'Se ponen rodajas de tomate, lechuga, filetes de pollo a la plancha, jamón de york, queso en lonchas y por último huevo a la plancha.',
    ],
  },
  {
    titulo: 'Berenjenas califales',
    momento: 'COMIDA',
    descripcion: 'Berenjenas en tempura con salsa de Pedro Ximénez',
    tiempo: 40,
    personas: 4,
    ingredientes: ['Berenjenas', 'Pedro Ximénez (200 ml)', 'Azúcar (20 gr)', 'Sal', 'Harina Yolanda (tempura)', 'Aceite', 'Papel de cocina'],
    pasos: [
      'En un cazo a fuego medio/bajo echamos 200 ml de Pedro Ximénez más 20 gr de azúcar y removemos hasta que coja textura como de miel. Reservamos.',
      'En un bol con bastante agua y sal pelamos y cortamos la berenjena en bastoncillos y tapamos para que no floten.',
      'A continuación se hace una tempura con harina Yolanda; secamos muy bien con papel de cocina, pasamos por la tempura y freímos en aceite.',
      'Una vez escurridos del aceite se pasan a un plato y se les echa por encima la salsa de Pedro Ximénez.',
    ],
  },
  {
    titulo: 'Carrilleras al vino tinto',
    momento: 'COMIDA',
    descripcion: 'Carrilleras guisadas en olla exprés',
    tiempo: 60,
    personas: 4,
    ingredientes: ['Carrilleras', 'Aceite', 'Cebolla grande', 'Zanahoria', 'Ajos', 'Tomate', 'Vino tinto', 'Pimienta', 'Sal', 'Tomillo', 'Clavos', 'Hoja de laurel'],
    pasos: [
      'Se cortan las carrilleras en cuatro trozos y en la olla exprés con un poco de aceite se sellan y reservan.',
      'Se añade un poco más de aceite, se echa una cebolla grande, una zanahoria a trocitos y tres dientes de ajo; cuando esté pochado se ralla un tomate y se añade un poco de agua dejando hervir un poco.',
      'Se tritura toda la verdura y se le añade un vaso ancho de vino tinto, pimienta, sal, tomillo, dos clavos y una hoja de laurel, y la carne.',
      'Se cubre de agua, se cierra la olla y se pone a hervir unos veinte minutos.',
    ],
  },
  {
    titulo: 'Espaguetis con nata y gambas',
    momento: 'COMIDA',
    descripcion: 'Pasta cremosa con gambas',
    tiempo: 30,
    personas: 4,
    ingredientes: ['Espaguetis', 'Gambas', 'Aceite', 'Cebolla', 'Ajos', 'Nata', 'Vino blanco', 'Sal', 'Ajo en polvo', 'Pimienta', 'Agua'],
    pasos: [
      'Se cuecen las cáscaras de las gambas en un cazo con un poco de aceite y cuando hiervan se le echa agua; se reserva el caldo.',
      'En una sartén se refríe una cebolla y ajos picados y, una vez pochados, se le añade un poco de caldo de gambas, nata, un poco de vino blanco, sal y ajo en polvo.',
      'Cuando la salsa haya reducido se añaden las gambas, un poco de pimienta y la pasta cocida.',
      'Se mezcla todo y se deja a fuego lento un par de minutos.',
    ],
  },
  {
    titulo: 'Espaguetis con roquefort',
    momento: 'COMIDA',
    descripcion: 'Pasta con salsa de roquefort',
    tiempo: 25,
    personas: 4,
    ingredientes: ['Espaguetis', 'Mantequilla', 'Roquefort', 'Queso rallado', 'Pimienta', 'Sal', 'Nata'],
    pasos: [
      'En una sartén se echa un poco de mantequilla y cuando se derrita se añade el roquefort.',
      'Una vez derretido se le añade un poco de otro queso rallado, pimienta y sal y por último un paquete de nata.',
      'Se mezcla con la pasta cocida y se sirve.',
    ],
  },
  {
    titulo: 'Espárragos verdes',
    momento: 'COMIDA',
    descripcion: 'Espárragos con majado de ajo y comino',
    tiempo: 35,
    personas: 4,
    ingredientes: ['Espárragos (lata)', 'Pan', 'Ajos', 'Vinagre', 'Sal', 'Aceite', 'Comino molido', 'Pimentón'],
    pasos: [
      'En primer lugar se hierven un poco los espárragos hasta que estén tiernos.',
      'En un poco de aceite se fríen unos tres o cuatro dientes de ajo en rodajas; cuando estén tiernos se apartan y se fríen en ese mismo aceite unas tres rebanadas de pan. Cuando estén doradas se echan en un plato hondo, se cubre de agua y se reserva.',
      'En el mortero se echa una cucharadita rasa de comino molido, los ajos y el pan sin escurrir y se maja todo junto.',
      'En ese mismo aceite se echa un poco de pimentón y, antes de que se queme, se le añaden los espárragos y el majado y se remueve un poco.',
      'A continuación se le añade vinagre, sal y un poco de agua y se deja hervir un poco.',
    ],
  },
  {
    titulo: 'Enchilada',
    momento: 'COMIDA',
    descripcion: 'Tortitas de taco al horno con pollo y alubias',
    tiempo: 40,
    personas: 4,
    ingredientes: ['Alubias rojas (bote)', 'Tortitas de tacos', 'Maíz', 'Queso rallado', 'Pollo', 'Guacamole', 'Tomate frito', 'Nata agria', 'Mantequilla'],
    pasos: [
      'En una sartén con un poco de aceite se echa el pollo desmenuzado y previamente cocido en agua con sal; encima las alubias rojas, el maíz y tomate frito.',
      'En una fuente para horno se unta un poco de mantequilla y se coloca una torta, el relleno anterior con queso rallado, otra torta, relleno y queso rallado y por último una torta con queso rallado.',
      'Al horno hasta que se derrita el queso sin llegar a tostar.',
      'Si se quiere, una vez sacado del horno se le puede echar encima un poco de guacamole y nata agria.',
    ],
  },
  {
    titulo: 'Crepes',
    momento: 'AMBAS',
    descripcion: 'Crepes dulces o salados',
    tiempo: 30,
    personas: 2,
    ingredientes: ['Leche (1 taza de café)', 'Harina (1 taza de café)', 'Huevo + una yema', 'Sal'],
    pasos: [
      'Se mezcla todo bien: una taza de café de leche, una taza de café de harina, un huevo más una yema y una pizca de sal.',
      'Se deja reposar una hora en el frigorífico.',
      'Se hacen en una sartén untada con mantequilla hasta que se doren por ambos lados.',
    ],
  },
  {
    titulo: 'Cuajada de patatas y bacon',
    momento: 'COMIDA',
    descripcion: 'Gratinado de patatas con bacon al horno',
    tiempo: 50,
    personas: 4,
    ingredientes: ['Cebollas', 'Bacon', 'Champiñones', 'Patatas', 'Nata', 'Queso rallado', 'Sal'],
    pasos: [
      'Se cuecen las patatas con sal y, cuando estén tiernas, se apartan.',
      'En una sartén se refríen las cebollas muy picaditas y luego los champiñones muy picaditos junto con el bacon a tiritas.',
      'A continuación se añaden las patatas y se les da unas vueltas.',
      'Se echa en una fuente para horno, se le añade nata y queso rallado y se gratina.',
    ],
  },
  {
    titulo: 'Galletas cookies rellenas',
    momento: 'POSTRE',
    descripcion: 'Cookies con corazón de chocolate',
    tiempo: 90,
    personas: 12,
    ingredientes: ['Mantequilla (130 gr)', 'Harina (300 gr)', 'Huevos', 'Levadura', 'Azúcar blanca (150 gr)', 'Azúcar moreno (50 gr)', 'Chips de chocolate', 'Tableta de chocolate (relleno)'],
    pasos: [
      'Se mezclan todos los ingredientes con un tenedor (pueden quedar grumos).',
      'Tapar con papel film transparente una cubitera de hielo y rellenar con la masa.',
      'Meter una onza de chocolate en el centro y cubrir con la masa.',
      'Espolvorear con harina, tapar con film transparente y congelar durante una hora.',
      'Pasado este tiempo meter al horno unos 15 minutos.',
    ],
  },
  {
    titulo: 'Garbanzos con choco y langostinos',
    momento: 'COMIDA',
    descripcion: 'Potaje de garbanzos con sepia y langostinos',
    tiempo: 90,
    personas: 6,
    ingredientes: ['Langostinos', 'Aceite', 'Vino dulce', 'Pimentón', 'Cebolla', 'Ajos', 'Zanahorias', 'Pimiento', 'Puerro', 'Laurel', 'Tomates', 'Choco (sepia)', 'Garbanzos remojados', 'Sal', 'Agua'],
    pasos: [
      'En un cazo con un poco de aceite se cuecen las cabezas de los langostinos y se aplastan para que saquen todo su jugo; a continuación se le añade vino dulce y pimentón.',
      'En la olla a presión con un poco de aceite se rehoga cebolla, ajos, zanahorias, pimiento, puerro y laurel y, una vez pochados, se añaden un par de tomates rallados.',
      'Se tritura toda la verdura que se quiera (cebolla, ajos y puerro).',
      'A continuación se le añade el choco limpio, el caldo de las cabezas de langostinos con un poco de sal y los garbanzos remojados; se cubre de agua y se cierra la olla durante unos 20 minutos.',
      'Por último se añaden los langostinos y se deja hervir hasta que estén cocidos.',
    ],
  },
  {
    titulo: 'Galette o quiche de merluza y gambas',
    momento: 'COMIDA',
    descripcion: 'Tarta salada de merluza y gambas',
    tiempo: 50,
    personas: 6,
    ingredientes: ['Aceite', 'Cebolla', 'Ajos', 'Bacon en tiras', 'Merluza', 'Gambas', 'Nata', 'Queso rallado', 'Orégano', 'Sal', 'Pimienta', 'Masa quebrada'],
    pasos: [
      'En una sartén con aceite se rehoga una cebolla, dos ajos y un paquete de bacon en tiras.',
      'Cuando ya está todo refrito se añade la merluza troceada y las gambas junto con un paquete de nata, dejándolo hervir un ratito.',
      'Por último se le echa queso rallado, orégano, sal y pimienta; se aparta y se deja enfriar.',
      'En un recipiente para horno se pone la masa quebrada, se le echa el relleno y se mete en el horno hasta que el relleno esté cuajado.',
    ],
  },
  {
    titulo: 'Huevos rotos con migas',
    momento: 'COMIDA',
    descripcion: 'Migas clásicas con huevos y chorizo',
    tiempo: 40,
    personas: 4,
    ingredientes: ['Pan del día anterior', 'Agua', 'Aceite', 'Chorizo', 'Ajos', 'Pimentón', 'Huevos', 'Jamón en lonchas'],
    pasos: [
      'El pan del día anterior se desmenuza y se humedece con un vaso de agua (salpicado); se tapa media hora.',
      'En una sartén con un poco de aceite se trocea chorizo y ajos machacados sin pelar con un poco de pimentón y rápidamente las migas hasta que queden doradas sin dejar de mover; se apartan en una fuente.',
      'Se fríen los huevos y se parten encima de las migas junto con unas lonchas de jamón.',
    ],
  },
  {
    titulo: 'Huevos rotos con gulas',
    momento: 'COMIDA',
    descripcion: 'Patatas con gulas al ajillo y huevos rotos',
    tiempo: 30,
    personas: 2,
    ingredientes: ['Patatas', 'Aceite', 'Gulas', 'Ajos', 'Huevos'],
    pasos: [
      'Se fríen patatas en rodajas no muy fritas, que queden tiernas.',
      'Por otro lado se hacen las gulas al ajillo.',
      'En un recipiente se colocan las patatas, encima las gulas y encima los huevos fritos; se rompen encima de las gulas.',
    ],
  },
  {
    titulo: 'Macarrones a la boloñesa',
    momento: 'COMIDA',
    descripcion: 'Macarrones con salsa boloñesa casera',
    tiempo: 40,
    personas: 4,
    ingredientes: ['Macarrones', 'Vino blanco', 'Sal', 'Cebollas', 'Carne picada', 'Ajos', 'Tomate frito'],
    pasos: [
      'En una sartén se refríen las cebollas y los ajos.',
      'Cuando esté pochadito se le añade la carne picada con un poco de sal, se le da unas vueltecitas y se le echa un chorreón de vino blanco.',
      'Cuando se ha consumido el vino, se pasa todo por la batidora (si no quieres que se note la cebolla y los ajos) y se le añade el tomate.',
      'Se cuece la pasta con sal y, una vez cocida, se mezcla con la salsa anterior.',
    ],
  },
  {
    titulo: 'Macarrones a la cazuela',
    momento: 'COMIDA',
    descripcion: 'Pasta al horno en cazuelitas de barro',
    tiempo: 30,
    personas: 4,
    ingredientes: ['Macarrones', 'Tomate frito', 'Chorizo', 'Atún', 'Queso rallado', 'Sal'],
    pasos: [
      'Se cuece la pasta en agua con sal y se reserva.',
      'En cazuelas de barro se empieza a echar: el chorizo a cuadraditos, el atún desmigado, la pasta y el tomate frito.',
      'Se le echa queso rallado y se mete en el microondas para que se funda.',
    ],
  },
  {
    titulo: 'Musaka (pastel de berenjenas)',
    momento: 'COMIDA',
    descripcion: 'Capas de patata, berenjena y carne con bechamel',
    tiempo: 60,
    personas: 6,
    ingredientes: ['Carne picada de cerdo y ternera', 'Tomate frito', 'Berenjenas', 'Sal', 'Cebolla', 'Bechamel', 'Patatas', 'Mantequilla', 'Queso rallado', 'Aceite'],
    pasos: [
      'Se hacen las patatas a rodajas en el microondas con un poquito de aceite y sal y, una vez tiernas, se ponen en una fuente para horno untada con un poco de mantequilla.',
      'Las berenjenas se hacen de la misma forma que las patatas y se reservan.',
      'En una sartén con un poco de aceite se refríen las cebollas y cuando estén pochaditas se le añade la carne picada con un poco de sal.',
      'Cuando ya está la carne refrita se tritura un poco junto con la berenjena añadiéndole un poco de tomate frito; se deja hacer un poco en la sartén y se coloca encima de las patatas.',
      'Se prepara la bechamel, se le echa queso rallado para gratinar y se mete en el horno.',
    ],
  },
  {
    titulo: 'Medallones de pollo',
    momento: 'COMIDA',
    descripcion: 'Medallones rebozados de pollo y queso',
    tiempo: 40,
    personas: 4,
    ingredientes: ['Pechuga de pollo', 'Sal', 'Pan bimbo', 'Salsa gaucha', 'Queso rallado', 'Huevo', 'Pan rallado', 'Aceite'],
    pasos: [
      'Cocemos la pechuga de pollo en agua con sal. Una vez que se enfríe la desmenuzamos.',
      'Aplastamos las rebanadas de pan bimbo con un rodillo y en el centro colocamos el pollo, salsa gaucha y queso rallado.',
      'Le colocamos otra rebanada aplastada encima y cortamos el centro con un vaso ancho.',
      'Rebozamos en huevo y pan rallado y freímos.',
    ],
  },
  {
    titulo: 'Lasaña de patata',
    momento: 'COMIDA',
    descripcion: 'Lasaña de patatas gratinada sin pasta',
    tiempo: 50,
    personas: 4,
    ingredientes: ['Patatas', 'Perejil', 'Jamón de York', 'Queso rallado', 'Queso en lonchas', 'Nata', 'Bacon en tiritas', 'Huevo', 'Mantequilla'],
    pasos: [
      'Se pelan las patatas, se cortan a rodajas y se hacen en el microondas.',
      'En una fuente para horno se unta con un poco de mantequilla y se empieza a colocar rodajas de patatas, jamón de york y queso en lonchas dos veces; encima bacón a tiras, un poco de perejil y patatas a rodajas.',
      'Por último se bate un huevo con un paquete de nata y se echa por encima con queso rallado.',
      'Se gratina en el horno.',
    ],
  },
];