// Recetas estructuradas extraidas de Recetas.Mar.docx (importadas por script).
// Parte 2 de 2.
import { RecetaImport } from './recetasDataA';

export const RECETAS_B: RecetaImport[] = [
  {
    titulo: 'Lentejas',
    momento: 'COMIDA',
    descripcion: 'Lentejas de la abuela',
    tiempo: 80,
    personas: 6,
    ingredientes: ['Lentejas', 'Zanahorias', 'Patatas o arroz', 'Sal', 'Cebolla', 'Laurel', 'Chorizo', 'Pimiento', 'Ajos', 'Morcilla', 'Tomate', 'Comino/pimienta', 'Pimentón', 'Avecrem', 'Hueso de jamón (opcional)', 'Aceite'],
    pasos: [
      'En un poco de aceite se echa toda la verdura picada y se refríe.',
      'Cuando ya está tierna se le echa el chorizo, la morcilla y el hueso de jamón (opcional); se remueve un poco.',
      'Se le añaden las lentejas, se vuelve a remover y por último se le echa un poco de pimentón, sal, una hoja de laurel y Avecrem.',
      'Dejar hervir hasta que el caldo espese y apartar.',
    ],
  },
  {
    titulo: 'Lomo al parmesano',
    momento: 'COMIDA',
    descripcion: 'Filetes de lomo gratinados con champiñones y queso',
    tiempo: 30,
    personas: 4,
    ingredientes: ['Filetes de lomo', 'Perejil', 'Queso en lonchas', 'Ajos', 'Tomate frito', 'Champiñones', 'Orégano', 'Sal', 'Pimienta', 'Aceite'],
    pasos: [
      'Se refríen los champiñones y los ajos picados y, una vez apartado, se le echa el perejil y se reserva.',
      'Se salpimentan los filetes, se fríen un poco y se colocan en una fuente para horno.',
      'Encima de cada filete se le echa un poco de tomate mezclado con orégano, los champiñones picados con los ajos y el queso en loncha.',
      'Se mete en el horno hasta que se gratine el queso.',
    ],
  },
  {
    titulo: 'Lomo hasselback',
    momento: 'COMIDA',
    descripcion: 'Cinta de lomo rellena de queso y bacon',
    tiempo: 90,
    personas: 6,
    ingredientes: ['Cinta de lomo', 'Queso en lonchas', 'Bacon en lonchas', 'Pinchos largos', 'Hilo grueso', 'Sal', 'Pimienta', 'Aceite', 'Mostaza'],
    pasos: [
      'Se le hacen unos cortes profundos a la cinta de lomo como si fuera para filetes sin llegar abajo del todo.',
      'Se coge una loncha de queso (el que más guste), doblada por la mitad, y se envuelve con una loncha de bacon; se mete en cada corte que se le ha hecho al lomo.',
      'Una vez rellena toda la cinta de lomo se atraviesa con unos pinchos largos y se ata con hilo grueso para que no se deshaga.',
      'Se le echa sal, pimienta, un chorrito de aceite y un poco de mostaza y al horno hasta que la carne esté hecha, aproximadamente una hora.',
    ],
  },
  {
    titulo: 'Nachos a la barbacoa',
    momento: 'CENA',
    descripcion: 'Nachos con pollo a la barbacoa',
    tiempo: 25,
    personas: 2,
    ingredientes: ['Pollo', 'Sal', 'Pimienta', 'Ajo en polvo', 'Pimentón picante', 'Salsa barbacoa', 'Nachos', 'Queso rallado', 'Guacamole', 'Nata agria'],
    pasos: [
      'Se corta el pollo en tiras pequeñas y se refríe en una sartén con sal, pimienta, ajo en polvo y pimentón picante.',
      'Cuando el pollo ya está hecho se le añade un poco de salsa barbacoa.',
      'En un recipiente para microondas se pone base de nachos y encima la carne con más queso rallado hasta que se derrita.',
      'Se le puede poner encima guacamole y nata agria.',
    ],
  },
  {
    titulo: 'Ñoquis a la carbonara',
    momento: 'COMIDA',
    descripcion: 'Ñoquis con salsa carbonara',
    tiempo: 25,
    personas: 4,
    ingredientes: ['Cebolla', 'Aceite', 'Bacon en tiras', 'Champiñones', 'Queso rallado', 'Nata', 'Ñoquis'],
    pasos: [
      'Se refríe la cebolla en un poco de aceite y, una vez tierna, se le añade el bacon en tiras, los champiñones y el queso rallado; por último, la nata.',
      'Se cuecen los ñoquis según las instrucciones del fabricante y se añaden a la salsa.',
    ],
  },
  {
    titulo: 'Pollo ras el hanout',
    momento: 'COMIDA',
    descripcion: 'Pollo en salsa especiada con nata',
    tiempo: 35,
    personas: 4,
    ingredientes: ['Pollo', 'Aceite', 'Cebolla', 'Ajo', 'Sal', 'Pimienta', 'Ras el Hanout', 'Nata', 'Tomate triturado (lata)'],
    pasos: [
      'Se corta el pollo en daditos, se fríe en una sartén y se reserva.',
      'En ese mismo aceite se refríe una cebolla y un ajo picados con un poco de sal y pimienta.',
      'Una vez pochado se le añade el Ras el Hanout, se remueve unos minutos y se añade nata y un poco de tomate triturado (lata).',
      'Se mete la carne y se deja hervir unos minutos.',
    ],
  },
  {
    titulo: 'Patatas panaderas',
    momento: 'COMIDA',
    descripcion: 'Patatas al estilo panadero con pimiento',
    tiempo: 40,
    personas: 4,
    ingredientes: ['Aceite', 'Cebolla', 'Pimiento', 'Ajo', 'Patatas', 'Sal'],
    pasos: [
      'En una sartén con aceite se refríe cebolla en juliana, pimiento a tiras y un ajo picadito.',
      'Cuando esté casi pochado se le echa encima las patatas a rodajas y se dejan que se pongan tiernas a fuego muy lento, sin dejar que se queme el refrito.',
    ],
  },
  {
    titulo: 'Pan de pueblo con gulas',
    momento: 'CENA',
    descripcion: 'Tostada de brie con gulas al ajillo',
    tiempo: 20,
    personas: 2,
    ingredientes: ['Pan de pueblo', 'Queso Brie', 'Gulas', 'Ajo', 'Aceite', 'Alioli'],
    pasos: [
      'Se tuestan rebanadas de pan de pueblo y encima se colocan finas tiras de queso Brie.',
      'Se colocan encima las gulas al ajillo previamente hechas y un poco de alioli.',
      'Se calienta en el microondas o en el horno.',
    ],
  },
  {
    titulo: 'Puchero',
    momento: 'COMIDA',
    descripcion: 'Puchero andaluz completo',
    tiempo: 100,
    personas: 8,
    ingredientes: ['Pollo', 'Garbanzos', 'Patata', 'Zanahoria', 'Ternera', 'Puerro', 'Sal', 'Apio', 'Avecrem', 'Hueso blanco', 'Costilla', 'Espinazo', 'Tocino fresco', 'Agua'],
    pasos: [
      'Se echa agua hasta la mitad en la olla exprés y se pone a fuego fuerte añadiendo todos los huesos lavados, el tocino, las verduras y los garbanzos una vez que el agua esté caliente.',
      'Cuando el agua esté hirviendo se le echa la carne y se espuma con un cazo; cuando no salga espuma se cierra la olla y se pone unos 20/25 minutos.',
      'Una vez pasado este tiempo se abre la olla, se saca un poco de caldo en un recipiente y se le añade un poco más de agua junto con la patata, sal y Avecrem, dejando hervir unos 10 minutos.',
      'Pasado este tiempo se le añade el caldo reservado y se le sacan todos los ingredientes.',
    ],
  },
  {
    titulo: 'Patatas empanadas',
    momento: 'COMIDA',
    descripcion: 'Capas de patata con atún gratinadas',
    tiempo: 45,
    personas: 4,
    ingredientes: ['Cebollas', 'Ajos', 'Aceite', 'Tomate frito', 'Atún', 'Patatas', 'Mantequilla', 'Queso rallado'],
    pasos: [
      'Se refríen cebollas y ajos y cuando esté tierno se le añade un poco de tomate frito; se deja hervir un poco y se añade el atún.',
      'Por otro lado se cortan las patatas en rodajas y se hacen en el microondas con un poco de aceite y sal; cuando estén tiernas se apartan.',
      'En una fuente para horno se unta con un poco de mantequilla y se coloca una tanda de patatas, el refrito anterior y por último otra tanda de patatas.',
      'Se le echa queso rallado y se gratina.',
    ],
  },
  {
    titulo: 'Revuelto campero',
    momento: 'COMIDA',
    descripcion: 'Revuelto con chorizo, morcilla y champiñones',
    tiempo: 35,
    personas: 4,
    ingredientes: ['Patatas', 'Aceite', 'Cebolla', 'Pimiento', 'Chorizo', 'Morcilla', 'Champiñones', 'Filetes de cerdo', 'Huevos', 'Sal', 'Pimienta'],
    pasos: [
      'Cocer unas patatas y reservar.',
      'En una sartén con un poco de aceite se refríe una cebolla, pimiento, rodajas de chorizo y morcilla.',
      'A continuación champiñones laminados y filetes cortados a trocitos pasados previamente por la sartén.',
      'Se añaden huevos para el revuelto con un poco de sal y pimienta.',
    ],
  },
  {
    titulo: 'Torta de cebolla caramelizada y queso de cabra',
    momento: 'COMIDA',
    descripcion: 'Tarta fina de hojaldre con cebolla y queso de cabra',
    tiempo: 45,
    personas: 4,
    ingredientes: ['Masa de hojaldre', 'Cebolla', 'Aceite', 'Azúcar', 'Tomillo', 'Huevo', 'Nata (100 gr)', 'Sal', 'Pimienta', 'Queso de cabra'],
    pasos: [
      'En un recipiente para horno se extiende la masa de hojaldre, se pincha con un tenedor para que no suba y se mete en el horno hasta que esté hecha.',
      'En un cazo con aceite se rehoga la cebolla en juliana y, cuando esté pochada, se le añade azúcar y un poco de tomillo.',
      'En un bol se bate un huevo y se le añade 100 gr de nata, un poco de sal y pimienta.',
      'Encima del hojaldre se pone la cebolla caramelizada, el huevo batido con la nata y encima rodajas de queso de cabra; al horno hasta que se cuaje.',
    ],
  },
  {
    titulo: 'Tarta tres chocolates',
    momento: 'POSTRE',
    descripcion: 'Tarta de tres chocolates con base de oreo',
    tiempo: 120,
    personas: 8,
    ingredientes: ['Nata líquida (750 ml)', 'Leche (750 ml)', 'Chocolate negro (150 gr)', 'Chocolate con leche (150 gr)', 'Chocolate blanco (150 gr)', 'Galletas oreo', 'Mantequilla', 'Cuajada (3 sobres)', 'Azúcar (75 gr)'],
    pasos: [
      'Se trituran las galletas junto con la mantequilla derretida y se pone en la base del molde de la tarta.',
      'Mezclamos 250 ml de leche, 250 ml de nata y apartamos 100 ml de esta mezcla en un bol con un sobre de cuajada; reservamos.',
      'Ponemos la mezcla grande en un cazo al fuego, añadimos el chocolate negro y 50 gr de azúcar hasta que hierva; retiramos y añadimos la cuajada apartada anteriormente, lo ponemos al fuego removiendo hasta que hierva y lo echamos en el molde hasta que se enfríe y cuaje.',
      'Seguimos con la segunda capa de chocolate con leche, todo igual pero solo añadimos 25 gr de azúcar. Una vez terminado se echa encima de la capa anterior hasta que cuaje.',
      'Seguimos con el chocolate blanco, todo igual pero sin azúcar, y se echa encima de la capa anterior hasta que cuaje.',
      'Meter en la nevera de 3 a 4 horas.',
    ],
  },
  {
    titulo: 'Tortilla de tacos',
    momento: 'COMIDA',
    descripcion: 'Tortita rellena con huevo al estilo tortilla',
    tiempo: 20,
    personas: 2,
    ingredientes: ['Mantequilla', 'Tortitas', 'Huevos', 'Sal', 'Pimienta', 'Pimentón dulce', 'Jamón de york', 'Tomate', 'Queso rallado'],
    pasos: [
      'En una sartén se pone un poco de mantequilla y cuando se derrita una tortita encima.',
      'En un bol se baten huevos, sal, pimienta y un poco de pimentón dulce y se echa encima de la tortita; se añade jamón de york, rodajas de tomate o tomate frito y queso rallado.',
      'Se coloca otra tortita encima hasta que cuaje y por último se le unta un poco de mantequilla a esta tortita y se le da la vuelta hasta que se dore un poco.',
    ],
  },
  {
    titulo: 'Tacos rellenos',
    momento: 'CENA',
    descripcion: 'Tortitas rellenas con distintas combinaciones',
    tiempo: 25,
    personas: 4,
    ingredientes: ['Tortitas', 'Queso rallado', 'Jamón de York', 'Queso de untar', 'Tomate', 'Bacon', 'Huevo', 'Queso en lonchas', 'Pollo cocido desmenuzado', 'Lechuga', 'Mayonesa', 'Aguacate'],
    pasos: [
      'Hacer un corte a las tortitas del centro hacia fuera, rellenar y doblar.',
      'Rellenos posibles: queso rallado; jamón de York; queso de untar con rodajas de tomate; bacon en lonchas frito; huevo revuelto; queso en lonchas; pollo cocido desmenuzado; lechuga con mayonesa; queso rallado; pollo cocido desmenuzado con queso en lonchas y aguacate.',
    ],
  },
  {
    titulo: 'Wrap de pollo y pimientos',
    momento: 'CENA',
    descripcion: 'Tortita rellena de pollo y pimientos al grill',
    tiempo: 20,
    personas: 2,
    ingredientes: ['Filetes de pollo', 'Aceite', 'Sal', 'Tortitas', 'Pimientos asados', 'Queso rallado', 'Salsa gaucha'],
    pasos: [
      'Se pasa por una sartén con un poco de aceite los filetes con un poco de sal.',
      'En la mitad de la tortita se echa pimientos asados, encima queso rallado, salsa gaucha o la que más guste y por último el filete.',
      'Se dobla por la mitad y se mete en el grill.',
    ],
  },
];